language: python
sudo: false
python:
  - "3.5"
install:
  - pip install ipykernel jupyter_client traitlets jupyter_kernel_test flit
  - flit install
  - python -m calysto_bash.install
script:
  - python test_bash_kernel.py
